### PR TITLE
Fix/image at user profile shouldnot have camera image and have a text

### LINKED ISSUE #159: image at user profile shouldnot have image and have a text
ImageImage

### PR DESCRIPTION
**Pull request by gehadepada**
before

image

after

image

### CODE REVIEW

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/UserProfileImage.kt [hunk 1]
```diff
@@ -73,35 +74,39 @@ fun UserProfileImage(
...
 
         if (!text.isNullOrEmpty()) {
             Text(
                 text = text,
                 style = Theme.textStyle.label.mediumMedium14,
-                color = Theme.color.surfaces.onSurfaceVariant
+                color = Theme.color.surfaces.onSurfaceVariant,
+                modifier=Modifier.padding(
+                    bottom = 32.dp
+                    ),
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/UserProfileImage.kt:109]: make it in one line

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/register/content/RegisterScreenContentUserNamePasswordDateOfBirth.kt [hunk 2]
```diff
@@ -110,10 +111,8 @@ private fun UserProfileStep(
             onImagePickerClick = onImagePickerClick,
             onImageRetrieved = onImageRetrieved,
             modifier = Modifier
-                .align(Alignment.CenterHorizontally)
-                .padding(
-                    bottom = 32.dp
-                )
+                .align(Alignment.CenterHorizontally),
+            text=stringResource(Res.string.upload_image)
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/register/content/RegisterScreenContentUserNamePasswordDateOfBirth.kt:115]: add space before and after the `=`

**Review by YoussefmSaber — APPROVED** [review]

**Review by MennaSrour — APPROVED** [review]
