### PR TITLE
fix/workout-details-loading

### LINKED ISSUE #225: Default values appear when loading instead of shimmer effect in workout details screen
Default values appear when loading instead of shimmer effect in workout details screen
Also the level card grows in size when it has a longer string like "intermediate"

https://github.com/user-attachments/assets/2fece27a-13ed-42df-92ae-d57efc8629c9

### PR DESCRIPTION
**Pull request by YoussefmSaber**
### Changes in this PR:
- Created loading screen for workout details screen

https://github.com/user-attachments/assets/546e8c8e-e4de-4d6f-9100-a33b45bfd3cf

### CODE REVIEW

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/workout_details/WorkoutDetailsViewModel.kt [hunk 1]
```diff
@@ -17,24 +17,38 @@ class WorkoutDetailsViewModel(
...
     private fun loadWorkoutSaveStatus(workoutId: String) {
         tryToCall(
+            onStart = { updateState { it.copy(isLoading = true) } },
             block = { manageWorkoutUseCase.getFavoriteWorkouts() },
             onSuccess = { updateWorkoutSaveStatus(workoutId, it) },
-            onError = { updateState { it.copy(isLoading = false) } },
-            onStart = { updateState { it.copy(isLoading = true) } }
+            onError = { updateState { it.copy(isLoading = false) } }
         )
     }
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/workout_details/WorkoutDetailsViewModel.kt:53]: I think there is no need for `isLoading = true` when fetching the save state

**Review by Al-Qassim — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/workout_details/WorkoutDetailsViewModel.kt (hunk 1 above)
Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/workout_details/WorkoutDetailsViewModel.kt:53]: it's to load make the loading state when retrieving the data even if it's saved, it will be in use when i implement the error handling part for this screen which will be made in other PR

**Review by gehadepada — APPROVED** [review]
