### PR TITLE
Fix/theme and language bottom sheet issue

### LINKED ISSUE #269: theme and language bottom sheet issue
the chosen theme in the more screen should be based on the app theme, not the state that is saved inside the view model

and if we don't confirm changing the theme, the theme state saved inside the more view model should reset to the actual app theme

same for language bottom sheet

Image

### PR DESCRIPTION
**Pull request by gehadepada**
https://github.com/user-attachments/assets/0f7e2d60-aab4-40b7-876b-b7dae0eb923f

### CODE REVIEW

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/ThemeBottomSheetContent.kt [hunk 1]
```diff
@@ -57,23 +58,22 @@ fun ThemeBottomSheetContent(
...
             icon = Res.drawable.light,
             onCheckedChange = { onSelectTheme(MoreScreenState.Theme.LIGHT) }
         )
-
         PrimaryButton(
             modifier = Modifier
                 .padding(bottom = 16.dp, top = 38.dp),
             text = stringResource(Res.string.confirm),
-            onClick = { onConfirm(state.currentTheme) },
+            onClick = { onConfirm(if (state.isDarkChecked)  MoreScreenState.Theme.DARK else MoreScreenState.Theme.LIGHT ) },
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/ThemeBottomSheetContent.kt]: make the logic of this function in the viewModel

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreViewModel.kt [hunk 2]
```diff
@@ -43,7 +42,15 @@ class MoreViewModel(
...
-            onSuccess = {languageCode -> updateState { it.copy(currentLanguage = languageCodeToLanguage(languageCode)) } },
+            onSuccess = { languageCode ->
+                updateState {
+                    it.copy(
+                        currentLanguage = languageCodeToLanguage(
+                            languageCode
+                        )
+                    )
+                }
+            },
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreViewModel.kt]: extract it to external function

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreViewModel.kt [hunk 3]
```diff
@@ -124,7 +129,7 @@ class MoreViewModel(
 
     override fun onConfirmChangeTheme(theme: MoreScreenState.Theme) {
         tryToCall(
-            block = {managePreferencesUseCase.saveTheme(theme)},
+            block = { managePreferencesUseCase.saveTheme(theme) },
             onSuccess = {
                 onSuccessChangeTheme()
                 sendEffect(MoreEffect.ChangeTheme(theme))
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreViewModel.kt]: extract this too while you at it

**Review by hagarabobakr — APPROVED** [review]

**Review by Al-Qassim — CHANGES_REQUESTED** [review]
if you change the selected item, and close the bottom sheet without confirmation, then the selected item should reset to the actual value

**Review by YoussefmSaber — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreScreenState.kt [hunk 4]
```diff
@@ -8,11 +8,11 @@ data class MoreScreenState(
     val isThemeBottomSheetEnabled: Boolean = false,
     val isLanguageBottomSheetEnabled: Boolean = false,
     val isLogoutBottomSheetEnabled: Boolean = false,
-    val isDarkChecked: Boolean = false,
-    val isEnglishChecked: Boolean = true,
     val currentTheme: Theme = Theme.LIGHT,
     val currentLanguage: Language = Language.ENGLISH,
     val profile: Profile = Profile(),
+    val tempTheme: Theme = Theme.LIGHT,
+    val tempLanguage: Language = Language.ENGLISH,
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreScreenState.kt:15]: no need to stor the temp theme and the temp language in the screen state

an easier approach is to store them in the composable itself
```
var tempTheme by remember { mutatbleStateOf(state.currentTheme) }
var lang...
```

this will take less code, and no additional code will be needed in the view model, and you will not need to handle the reset logic if the user don't confirm

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreScreenState.kt:15]: see how I made it with the height, weight, workout days, tools, in the edit profile screen

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreViewModel.kt [hunk 5]
```diff
@@ -61,15 +64,15 @@ class MoreViewModel(
     }
 
     override fun onThemeClicked() {
-        updateState { it.copy(isThemeBottomSheetEnabled = true) }
+        updateState { it.copy(isThemeBottomSheetEnabled = true,tempTheme = it.currentTheme) }
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreViewModel.kt:67]: CTRL ALT SHIFT L
CTRL ALT SHIFT L
CTRL ALT SHIFT L

**Review by Al-Qassim — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreScreenState.kt (hunk 4 above)
Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreScreenState.kt:15]: we use the screen state in the viewModel to save the states for it as it will be changed internaly why do we make the logic of setting and getting the values in the screen and there is view model with screen states that's doing the same thing.

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/more/MoreScreenState.kt:15]: not all variables need to be stored in the screen state

no need to save the state of the temp choice in view model Youssef, it's a temp variable

image
