### PR TITLE
Fix/issues at personal information screen and more screen

### LINKED ISSUE #290: more screen, there should be units
Image

Image

### LINKED ISSUE #291: personal information screen, units of height and weight, and height should be an integrer
units & height should be integer

Image

### PR DESCRIPTION
**Pull request by hagarabobakr**

### CODE REVIEW

**Review by YoussefmSaber — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt [hunk 1]
```diff
@@ -192,7 +192,8 @@ fun PersonInfo(
             modifier = Modifier.weight(1f),
             icon = Res.drawable.ic_ruler,
             name = stringResource(Res.string.height),
-            value = Formatter.toString(height, 1)
+            value = formatHeightWeight(height),
+            measurementUnit = "cm"
```
Comment (ElsayedMagdy122) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt]: localization

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt [hunk 2]
```diff
@@ -204,7 +205,8 @@ fun PersonInfo(
             modifier = Modifier.weight(1f),
             icon = Res.drawable.weight,
             name = stringResource(Res.string.weight),
-            value = Formatter.toString(weight, 1)
+            value = formatHeightWeight(weight),
+            measurementUnit = "kg"
```
Comment (ElsayedMagdy122) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt]: same

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt [hunk 3]
```diff
@@ -237,7 +244,7 @@ fun EditProfileScreenContent(
 
                     LabeledInputField(
                         label = stringResource(Res.string.weight),
-                        value = (round(state.profile.weight * 10) / 10).toString(),
+                        value = "${formatHeightWeight(state.profile.weight)} kg",
```
Comment (ElsayedMagdy122) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt]: same

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt [hunk 4]
```diff
@@ -226,7 +233,7 @@ fun EditProfileScreenContent(
                 ) {
                     LabeledInputField(
                         label = stringResource(Res.string.height),
-                        value = (round(state.profile.height * 10) / 10).toString(),
+                        value = "${formatHeightWeight(state.profile.height)} cm",
```
Comment (ElsayedMagdy122) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt]: same

**Review by ElsayedMagdy122 — APPROVED** [review]
