### PR TITLE
fix play workout ui issues

### LINKED ISSUE #266: play workout, play screen
text weight issue, and the indecator should move with the timer and change the image every 10 seconds if possible

Image

### LINKED ISSUE #274: play workout, rest screen
Image

### PR DESCRIPTION
**Pull request by Al-Qassim**
https://github.com/user-attachments/assets/d1f0d350-e1fe-4468-942e-7307af9a7761

### CODE REVIEW

**Review by YoussefmSaber — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt [hunk 1]
```diff
@@ -302,13 +330,15 @@ private fun BottomButtons(
...
+                .clickable(onClick = onClickForward, enabled = isForwardButtonEnabled)
                 .background(Theme.color.surfaces.surfaceContainer)
                 .padding(12.dp)
                 .scale(scaleX = if (isRTL) -1f else 1f, scaleY = 1f),
             painter = painterResource(Res.drawable.ic_next_arrow),
             contentDescription = stringResource(Res.string.next),
-            tint = Theme.color.surfaces.onSurfaceContainer,
+            tint =
+                if (isForwardButtonEnabled) Theme.color.surfaces.onSurfaceContainer
+                else Theme.color.surfaces.outlineVariant,
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt:341]: use animate color as state instead of if statement

**Review by YoussefmSaber — CHANGES_REQUESTED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt (hunk 1 above)
Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt:341]: every exercise page has either true or false, this will not change during run time, so no animation is needed

Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt:341]: no it will change, it will make a fade animation as it's better just trust the process, remember there is option that skips the exercise so this will help animating the change of the color

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt:341]: watch the attached video, still no need for animation here, the enable state will not change, because we have 8 buttons in the screen, not 1

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt:341]: image

Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/playWorkout/content/PlayWorkoutContentPerform.kt:341]: ok so it will be initialized for every screen, i thought the screen content it self being redrawn

**Review by YoussefmSaber — APPROVED** [review]

**Review by hagarabobakr — APPROVED** [review]
