### PR TITLE
Fix/play button in home

### LINKED ISSUE #271: no play button in the workout card in the home screen
Image

### PR DESCRIPTION
**Pull request by iZyadNasser**

### CODE REVIEW

**Review by ElsayedMagdy122 — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/WorkoutCard.kt [hunk 1]
```diff
@@ -108,19 +110,21 @@ fun WorkoutCard(
...
+                        .padding(end = 4.dp)
+                        .clip(CircleShape)
+                        .background(Theme.color.surfaces.onSurfaceAt2),
+                    contentAlignment = Alignment.Center
+                ) {
+                    Icon(
+                        modifier = Modifier.padding(10.dp),
+                        tint = Theme.color.brand.primary,
+                        painter = painterResource(Res.drawable.ic_play),
+                        contentDescription = "Play Button"
```
Comment (hagarabobakr) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/WorkoutCard.kt]: localize this string

**Review by hagarabobakr — APPROVED** [review]
