### PR TITLE
fix issues with the fields of the edit profile

### LINKED ISSUE #330: edit profile screen, issue with units
Image

### PR DESCRIPTION
**Pull request by Al-Qassim**
https://github.com/user-attachments/assets/0bb4315b-ce58-49aa-a223-64d0c1b2694b

### CODE REVIEW

**Comment by gehadepada** [comment]
الtexts حاساها مقطوعة من تحت؟
full Name

**Comment by gehadepada** [comment]
في اكسترا بادينج عن فيجما ,تقريبا نادين لما ضافت الايكون البادينج باظ
image

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt [hunk 1]
```diff
@@ -459,18 +458,5 @@ private fun mapMainGoalToString(goal: FitnessGoal): String {
         FitnessGoal.LOSE_WEIGHT -> stringResource(Res.string.lose_weight)
         FitnessGoal.GAIN_WEIGHT -> stringResource(Res.string.gain_weight)
         FitnessGoal.STAY_IN_SHAPE -> stringResource(Res.string.stay_in_shape)
-
     }
-}
-
```
Comment (hagarabobakr) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt:465]: Why did you delete it?

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt [hunk 2]
```diff
@@ -224,18 +244,6 @@ fun PersonInfo(
     }
 }
```
Comment (hagarabobakr) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt:246]: Why did you delete it?

**Review by hagarabobakr — COMMENTED** [review]
image
In the design, the numbers are integers except when there is a .5.

**Comment by hagarabobakr** [comment]
> image In the design, the numbers are integers except when there is a .5.

**Comment by hagarabobakr** [comment]
image


same

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt (hunk 1 above)
Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/editProfile/EditProfileScreen.kt:465]: I removed the formatting function, because this is not a good place for it, I moved it to the util package, and improved on it

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt (hunk 2 above)
Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/more/content/MoreScreenContent.kt:246]: I removed the formatting function, because this is not a good place for it, I moved it to the util package, and improved on it

**Comment by Al-Qassim** [comment]
@hagarabobakr some numbers in figma are just examples, we can control the decimal places in the app

also, what's special about `.5` ? either put the decimal place or not, especially for the weight, most users will care so much about the exact weight

image

**Comment by Al-Qassim** [comment]
@gehadepada 
fixed the padding issue

image

**Review by gehadepada — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/LabeledInputField.kt [hunk 3]
```diff
@@ -35,24 +34,24 @@ fun LabeledInputField(
...
             Text(
                 text = label,
-                style = Theme.textStyle.label.smallRegular12.copy(
-                    color = Theme.color.surfaces.onSurfaceVariant
-                ),
-                modifier = Modifier.weight(1f)
+                style = Theme.textStyle.label.smallRegular12,
+                color = Theme.color.surfaces.onSurfaceVariant,
+                modifier = Modifier
+                    .weight(1f)
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/design_system/component/LabeledInputField.kt:46]: put modifier at first

**Review by YoussefmSaber — APPROVED** [review]
