### PR TITLE
Fix/report screen

### LINKED ISSUE #280: report screen
1. wrong radius for rounded corners
2. the arrow should be up when the drop down is open
3. there should be a shadow for the drop down
4. the space is too big between the title bar and the cards below

Image

### PR DESCRIPTION
**Pull request by YoussefmSaber**
https://github.com/user-attachments/assets/73c247c3-a8c6-4d51-b771-3dad55894a81

### CODE REVIEW

**Review by ElsayedMagdy122 — APPROVED** [review]

**Review by hagarabobakr — APPROVED** [review]

**Comment by Al-Qassim** [comment]
put the shadow on the animated viability, not on the box, and make the shadow color animated from transparent to the actual color

this will resolve the issue of the shadow appearing suddenly 

I did that with the snack bar, and it worked

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt [hunk 1]
```diff
@@ -72,27 +75,30 @@ fun DropdownMenu(
     onDismissRequest: () -> Unit,
     modifier: Modifier = Modifier,
 ) {
+    val dropShadowColor by animateColorAsState(
+        targetValue = if (isExpanded) Theme.color.surfaces.dropShadow else Color.Transparent
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: don't use `Color.Transparent`, this may cause a flickering, use `Theme.color.surfaces.dropShadow.copy(alpha = 0)`

**Review by Al-Qassim — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt (hunk 1 above)
Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: it's the same thing
what you did there just made it's alpha with 0 same as transparent

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: no youssef, it will not be the same in between, when the interpolation happens, it will interpolate between the blue, red, grean, and alpha. not just alpha

I'm just saying it may cause a flickering, I faced many cases before with such flickering, and this solution solved it

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: ok, I just checked that no problem will happen in your case, but keep it in you mind for the future

```
val animatedColor by animateColorAsState(
    targetValue = if (condition) myColor else Color.Transparent // this may cause flickering
)

val animatedColor by animateColorAsState(
    targetValue = if (condition) myColor else myColor.copy(alpha = 0f) // this will not
)
```

Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: ok
