### PR TITLE
Fix/when open favourite screen empty screen appear first

### LINKED ISSUE #284: when open favourite screen empty screen appear first
https://github.com/user-attachments/assets/1b08bc2a-c6e3-4cac-a076-bc4dfa8455fe

### PR DESCRIPTION
**Pull request by hagarabobakr**

### CODE REVIEW

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt:1]: You should add error handling to the screen, not just creating a state where there is loading or success, we should also handle errors

Comment (hagarabobakr) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt:1]: This branch is only for fixing the issue of the empty list appearing when accessing the favorites screen. Please take a look at the issue related to the pull request.

Comment (hagarabobakr) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt:1]: The error handling will be done in a separate branch.

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt [hunk 1]
```diff
@@ -93,33 +94,39 @@ fun TabsWithPager(
...
+                        else -> AnimatedEmptyStateSwitcher(
+                            isEmpty = meals.isEmpty(),
+                            emptyTitle = stringResource(Res.string.empty_meals_title),
+                            emptyDescription = stringResource(Res.string.empty_meals_description)
+                        ) {
+                            MealsList(
+                                meals = meals,
+                                onSaveIconClick = {
+                                    listener.deleteMeal(it)
+                                }
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt]: if you are going to use it then it's better to use call by reference like this
onSaveIconClick = listener::deleteMeal

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt [hunk 2]
```diff
@@ -93,33 +94,39 @@ fun TabsWithPager(
...
+                        else -> AnimatedEmptyStateSwitcher(
+                            isEmpty = workouts.isEmpty(),
+                            emptyTitle = stringResource(Res.string.empty_workouts_title),
+                            emptyDescription = stringResource(Res.string.empty_workouts_description)
+                        ) {
+                            WorkoutList(
+                                workouts = workouts,
+                                onSaveIconClick = {
+                                    listener.deleteWorkout(it)
+                                }
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/favorites/content/componants/TabsWithPager.kt]: if you are going to use it then it's better to use call by reference like this
onSaveIconClick = listener::deleteMeal

**Review by YoussefmSaber — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt [hunk 3]
```diff
@@ -107,24 +110,38 @@ class FavoritesViewModel(
...
+        loadingWorkoutsState(false)
+        updateState { it.copy(workoutsList = workouts.map { it.toUiState() }) }
+    }
+
+    private fun loadingMealsState(isLoading: Boolean) =
+        updateState { it.copy(isMealsLoading = isLoading) }
+
+    private fun loadingWorkoutsState(isLoading: Boolean) =
+        updateState { it.copy(isWorkoutsLoading = isLoading) }
+
```
Comment (ElsayedMagdy122) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt]: The names do not indicate the function's function, as it performs an update, while the current names indicate that it is a variable that returns a value.

rename to ex :  updateLoadingMealState

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt [hunk 4]
```diff
@@ -107,24 +109,38 @@ class FavoritesViewModel(
...
         )
     }
 
+    private fun onloadWorkoutsSuccess(workouts: List<WorkoutSuggested>) {
+        updateLoadingWorkoutsState(false)
+        updateState { it.copy(workoutsList = workouts.map { it.toUiState() }) }
+    }
+
+    private fun updateLoadingMealState(isLoading: Boolean) =
+        updateState { it.copy(isMealsLoading = isLoading) }
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt:139]: don't use compact notation for function if they are not only one line

Comment (Al-Qassim) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt:139]: also you don't need a separate function for this any way
it's only one line, put it directly in the try to call function

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesState.kt [hunk 5]
```diff
@@ -6,6 +6,8 @@ import com.cairosquad.evolvefit.domain.model.MealType
 
 data class FavoritesState(
     val isLoading: Boolean = false,
+    val isMealsLoading: Boolean = false,
+    val isWorkoutsLoading: Boolean = false,
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesState.kt:10]: you should not have 3 states for loading, either keep `isLoading` and remove the other two, or visa versa

**Review by Al-Qassim — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesState.kt (hunk 5 above)
Comment (hagarabobakr) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesState.kt:10]: In this case, I need more than one variable for loading.

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt (hunk 4 above)
Comment (hagarabobakr) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/favorites/FavoritesViewModel.kt:139]: Ok
