### PR TITLE
Fix/nutrition issues

### LINKED ISSUE #207: wrong padding at meal history item
figma

Image

our app

Image

### PR DESCRIPTION
**Pull request by ElsayedMagdy122**
# Enhance error handling in NutritionViewModel
fix :  #207

### CODE REVIEW

**Review by YoussefmSaber — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/nutrition/ManageNutritionUseCase.kt [hunk 1]
```diff
@@ -39,50 +46,56 @@ class ManageNutritionUseCase(private val nutritionRepository: NutritionRepositor
...
+    private fun parseCalories(input: String): Int {
+        return input.toIntOrNull() ?: throw InvalidNumberFormatException(FieldType.MEAL_CALORIES)
     }
-}
 
-private fun validateNumberInput(value: String) {
-    val regex = Regex("^[0-9]*\\.?[0-9]*$")
-    if (!regex.matches(value)) {
-        throw InvalidNumberFormatException()
+    private fun validateRemainingCalories(calories: Int, remainingCalories: Float) {
```
Comment (gehadepada) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/domain/usecase/nutrition/ManageNutritionUseCase.kt:96]: i think you can make both integer

**Review by gehadepada — APPROVED** [review]
