### PR TITLE
fix: drop menu dismiss if it's clicked on any thing else.

### LINKED ISSUE #270: should close the drop down menu when clicking on the button again, or click out side
Image

### PR DESCRIPTION
**Pull request by YoussefmSaber**
https://github.com/user-attachments/assets/5a07f03a-d388-4bf7-a698-47485265e925

### CODE REVIEW

**Review by gehadepada — APPROVED** [review]

**Review by ElsayedMagdy122 — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt [hunk 1]
```diff
@@ -22,7 +26,7 @@ import com.cairosquad.evolvefit.viewmodel.report.ReportScreenState
 import org.jetbrains.compose.resources.stringResource
 
 @Composable
-fun DropdownMenu(
+fun ShadowedDropdownMenu(
```
Comment (Al-Qassim) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: keep the name as `DropdownMenu`

**Review by Al-Qassim — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt (hunk 1 above)
Comment (YoussefmSaber) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: done

Comment (gehadepada) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/component/DropdownMenu.kt]: i think he will add shadow at another branch so he  rename it
