### PR TITLE
fix/edit-profile-placeholder-image-issue

### LINKED ISSUE #275: edit profile, placeholder image issue
Image

### PR DESCRIPTION
**Pull request by gehadepada**
image

### CODE REVIEW

**Review by hagarabobakr — APPROVED** [review]

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/register/RegisterViewModel.kt [hunk 1]
```diff
@@ -293,7 +288,10 @@ class RegisterViewModel(
             ) == true
 
         when {
-            error is NetworkException && error.message?.contains("User already exists", ignoreCase = true) == true -> {
+            error is NetworkException && error.message?.contains(
+                "User already exists",
```
Comment (ElsayedMagdy122) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/register/RegisterViewModel.kt:292]: store this value in variable

**Review by ElsayedMagdy122 — APPROVED** [review]

**Review by Al-Qassim — COMMENTED** [review]
make sure the image has not been corrupted in the edit profile screen and the registration screen
check both the cases of selecting an image, and not selecting an image
I checked it Qassim , I already separated register image logic and edit profile image logic 
There is a RigisterUserProfile at separated file

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/register/RegisterViewModel.kt (hunk 1 above)
Comment (gehadepada) [reply composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/register/RegisterViewModel.kt:292]: It is not related to this pr , I just made format
