### PR TITLE
Fix/put exercises image

### LINKED ISSUE #190: fix put exercises image

### PR DESCRIPTION
**Pull request by hagarabobakr**

### CODE REVIEW

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/exercise/CreateExerciseViewModel.kt [hunk 1]
```diff
@@ -87,79 +83,126 @@ class CreateExerciseViewModel(
...
+                    imageFileData.fileName,
+                    id
+                )
+                uploadedImage
+            },
+            onSuccess = {},
+            onError = {}
+
+        )
+    }
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/exercise/CreateExerciseViewModel.kt]: split the block to external function

**Review by Al-Qassim — APPROVED** [review]
very good job, just break down the big function in the view model

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/exercise/CreateExerciseViewModel.kt [hunk 2]
```diff
@@ -87,79 +83,126 @@ class CreateExerciseViewModel(
...
+
+    private fun getEquipments() {
+        tryToCall(
+            block = { manageEquipmentUseCase.getAllEquipments() },
+            onSuccess = { equipments ->
+                updateState {
+                    it.copy(availableEquipments = equipments.map { it.toUiState() }.toSet())
+                }
+            },
+            onError = { updateState { it.copy(errorMessage = "Failed to load equipments") } }
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/exercise/CreateExerciseViewModel.kt]: extract the onSUccess and onError to external functions

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/exercise/CreateExerciseViewModel.kt [hunk 3]
```diff
@@ -87,79 +84,128 @@ class CreateExerciseViewModel(
...
+        setLoadingState(true)
         tryToCall(
             onStart = { updateState { it.copy(isExerciseSaved = true) } },
             block = ::saveExercise,
-            onSuccess = { sendEffect(CreateExerciseEffect.NavigateToAllExercises) },
-            onError = {  },
+            onSuccess = { it ->
+                pushFrontImage(it)
+                pushBackImage(it)
+            },
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/viewmodel/exercise/CreateExerciseViewModel.kt:112]: make it one function that calls those 2 functions, we need to be consistant with our code so the on success is only one function that calls whatever inside it

**Review by MennaSrour — APPROVED** [review]
