### PR TITLE
fix: create workout, use exercise response data class to receive the api resonance, add bottom sheet to confirm cancellation, and fix ui issues

### LINKED ISSUE #346: create workout, need a bottom sheet for cancel
Image

### LINKED ISSUE #348: create workout, when creating a workout, we should navigate back to all workouts screen
https://github.com/user-attachments/assets/807da874-9260-48bd-b4e9-c07b7265bf5a

### PR DESCRIPTION
**Pull request by Al-Qassim**
https://github.com/user-attachments/assets/4424e992-5a9d-49ac-92f8-ecbdebaaa9e1

### CODE REVIEW

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/createExercise/content/CreateExerciseScreenContent.kt [hunk 1]
```diff
@@ -121,169 +125,157 @@ fun CreateExerciseScreenContent(
...
+            onImageRetrieved = listener::onEndImageRetrieved,
+            onImagePickerDismiss = listener::onEndImagePickerDismiss
+        )
+    }
 
+    ExitCreationBottomSheet(
+        isVisible = state.showExitBottomSheet,
+        onDismiss = listener::onCancelClicked,
+        onCancelClicked = { listener.onCancelClicked() },
+        onExitWithoutSavingClicked = { listener.onExitWithoutSavingClicked() },
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/createExercise/content/CreateExerciseScreenContent.kt]: call by reference, `listener::onCancelClicked`, `listener::onExitWithoutSavingClicked`

File: composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/createWorkout/CreateWorkoutScreen.kt [hunk 2]
```diff
@@ -33,19 +40,41 @@ fun CreateWorkoutScreen(
...
+                listener = listener
             )
         }
     }
+
+    ExitCreationBottomSheet(
+        isVisible = state.showExitBottomSheet,
+        onDismiss = listener::onCancelExitClicked,
+        onCancelClicked = { listener.onCancelExitClicked() },
+        onExitWithoutSavingClicked = { listener.onExitConfirmClicked() },
```
Comment (YoussefmSaber) [inline composeApp/src/commonMain/kotlin/com/cairosquad/evolvefit/ui/screen/createWorkout/CreateWorkoutScreen.kt]: use call by reference

**Review by YoussefmSaber — APPROVED** [review]

**Review by ElsayedMagdy122 — APPROVED** [review]

**Review by hagarabobakr — APPROVED** [review]
